### PR TITLE
Issue #31: Chore: Make a new logo suitable for the project

### PR DESCRIPTION
**Pull request by Ayush-Shukla02**
-> Added the logo images in public/Images and src/Images.
-> Updated the README.md file with the logo.

### CODE REVIEW

**Comment by Ayush-Shukla02** [comment]
@OmGuptaIND  the check failed. Any issue from my end?

**Comment by OmGuptaIND** [comment]
@AkMo3 why these error appear any idea and if so please tell is it because this file doesn't have access to the repo ?.

**Comment by OmGuptaIND** [comment]
else @Ayush-Shukla02 its done

**Comment by Ayush-Shukla02** [comment]
yes all is done only pr left

**Pull request merged**
