### PR TITLE
Issue #14: Added Navbar Component

### LINKED ISSUE #14: NavBar Component
Create navbar component for the front page.

mentor - @OmGuptaIND

### PR DESCRIPTION
**Pull request by OmGuptaIND**

### CODE REVIEW

**Comment by OmGuptaIND** [comment]
Review and Merge @AkMo3 @DreadArceus

**Comment by AkMo3** [comment]
@OmGuptaIND Please look
Screenshot from 2021-03-28 00-28-02

**Comment by OmGuptaIND** [comment]
yes after this merger this should work fine
filename mismatch not happening in my VS but was happening here I didn't knew this make a problem also but I fixed it

**Comment by OmGuptaIND** [comment]
Please check Again

**Comment by AkMo3** [comment]
Fix commit to push kar do. Maine apka branch ko hi clone karke run kara tha, tabhi ye aaya

**Review by AkMo3 — APPROVED** [review]

**Review by DreadArceus — APPROVED** [review]

**Pull request merged**
