### PR TITLE
Issue #7: Added Prettier Action

### PR DESCRIPTION
**Pull request by OmGuptaIND**
Added the Prettier Action For the issue please review and merge 

Tasks Done:

1. Added the Prettier.yml
2. Populated it with the code
3. Added the with Change query

### CODE REVIEW

**Comment by OmGuptaIND** [comment]
Please Help me why it is showing Conflicts now...

**Review by AkMo3 — CHANGES_REQUESTED** [review]
Add `commit_message` to workflow. Make it something like `chore: prettified code`

**Comment by AkMo3** [comment]
> Please Help me why it is showing Conflicts now...

There aren't any conflicts.

**Comment by AkMo3** [comment]
10 files kyu hai? Koi aur issue bhi sath mai merged hai kya?

**Comment by OmGuptaIND** [comment]
Updated the Code Review and check

**Comment by AkMo3** [comment]
> 10 files kyu hai? Koi aur issue bhi sath mai merged hai kya?

?

**Pull request closed without merging**
